// Generated by gencpp from file cashier_sys/updateResponse.msg
// DO NOT EDIT!


#ifndef CASHIER_SYS_MESSAGE_UPDATERESPONSE_H
#define CASHIER_SYS_MESSAGE_UPDATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cashier_sys
{
template <class ContainerAllocator>
struct updateResponse_
{
  typedef updateResponse_<ContainerAllocator> Type;

  updateResponse_()
    : status()  {
    }
  updateResponse_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::cashier_sys::updateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cashier_sys::updateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct updateResponse_

typedef ::cashier_sys::updateResponse_<std::allocator<void> > updateResponse;

typedef boost::shared_ptr< ::cashier_sys::updateResponse > updateResponsePtr;
typedef boost::shared_ptr< ::cashier_sys::updateResponse const> updateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cashier_sys::updateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cashier_sys::updateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cashier_sys::updateResponse_<ContainerAllocator1> & lhs, const ::cashier_sys::updateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cashier_sys::updateResponse_<ContainerAllocator1> & lhs, const ::cashier_sys::updateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cashier_sys

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cashier_sys::updateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cashier_sys::updateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cashier_sys::updateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cashier_sys::updateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cashier_sys::updateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cashier_sys::updateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cashier_sys::updateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::cashier_sys::updateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::cashier_sys::updateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cashier_sys/updateResponse";
  }

  static const char* value(const ::cashier_sys::updateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cashier_sys::updateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n"
;
  }

  static const char* value(const ::cashier_sys::updateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cashier_sys::updateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct updateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cashier_sys::updateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cashier_sys::updateResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASHIER_SYS_MESSAGE_UPDATERESPONSE_H
