// Generated by gencpp from file cashier_sys/update.msg
// DO NOT EDIT!


#ifndef CASHIER_SYS_MESSAGE_UPDATE_H
#define CASHIER_SYS_MESSAGE_UPDATE_H

#include <ros/service_traits.h>


#include <cashier_sys/updateRequest.h>
#include <cashier_sys/updateResponse.h>


namespace cashier_sys
{

struct update
{

typedef updateRequest Request;
typedef updateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct update
} // namespace cashier_sys


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cashier_sys::update > {
  static const char* value()
  {
    return "d0089fd6bf7209a8b647fde121195743";
  }

  static const char* value(const ::cashier_sys::update&) { return value(); }
};

template<>
struct DataType< ::cashier_sys::update > {
  static const char* value()
  {
    return "cashier_sys/update";
  }

  static const char* value(const ::cashier_sys::update&) { return value(); }
};


// service_traits::MD5Sum< ::cashier_sys::updateRequest> should match
// service_traits::MD5Sum< ::cashier_sys::update >
template<>
struct MD5Sum< ::cashier_sys::updateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cashier_sys::update >::value();
  }
  static const char* value(const ::cashier_sys::updateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cashier_sys::updateRequest> should match
// service_traits::DataType< ::cashier_sys::update >
template<>
struct DataType< ::cashier_sys::updateRequest>
{
  static const char* value()
  {
    return DataType< ::cashier_sys::update >::value();
  }
  static const char* value(const ::cashier_sys::updateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cashier_sys::updateResponse> should match
// service_traits::MD5Sum< ::cashier_sys::update >
template<>
struct MD5Sum< ::cashier_sys::updateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cashier_sys::update >::value();
  }
  static const char* value(const ::cashier_sys::updateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cashier_sys::updateResponse> should match
// service_traits::DataType< ::cashier_sys::update >
template<>
struct DataType< ::cashier_sys::updateResponse>
{
  static const char* value()
  {
    return DataType< ::cashier_sys::update >::value();
  }
  static const char* value(const ::cashier_sys::updateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CASHIER_SYS_MESSAGE_UPDATE_H
