# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cashier_sys/bill.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class bill(genpy.Message):
  _md5sum = "360bbffaaae293a5eb667a3b95f35443"
  _type = "cashier_sys/bill"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 BillNumber
time Timestamp
int64 Quantity
float64 Price
float64 Total
"""
  __slots__ = ['BillNumber','Timestamp','Quantity','Price','Total']
  _slot_types = ['int64','time','int64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       BillNumber,Timestamp,Quantity,Price,Total

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(bill, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.BillNumber is None:
        self.BillNumber = 0
      if self.Timestamp is None:
        self.Timestamp = genpy.Time()
      if self.Quantity is None:
        self.Quantity = 0
      if self.Price is None:
        self.Price = 0.
      if self.Total is None:
        self.Total = 0.
    else:
      self.BillNumber = 0
      self.Timestamp = genpy.Time()
      self.Quantity = 0
      self.Price = 0.
      self.Total = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q2Iq2d().pack(_x.BillNumber, _x.Timestamp.secs, _x.Timestamp.nsecs, _x.Quantity, _x.Price, _x.Total))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Timestamp is None:
        self.Timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.BillNumber, _x.Timestamp.secs, _x.Timestamp.nsecs, _x.Quantity, _x.Price, _x.Total,) = _get_struct_q2Iq2d().unpack(str[start:end])
      self.Timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q2Iq2d().pack(_x.BillNumber, _x.Timestamp.secs, _x.Timestamp.nsecs, _x.Quantity, _x.Price, _x.Total))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Timestamp is None:
        self.Timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.BillNumber, _x.Timestamp.secs, _x.Timestamp.nsecs, _x.Quantity, _x.Price, _x.Total,) = _get_struct_q2Iq2d().unpack(str[start:end])
      self.Timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q2Iq2d = None
def _get_struct_q2Iq2d():
    global _struct_q2Iq2d
    if _struct_q2Iq2d is None:
        _struct_q2Iq2d = struct.Struct("<q2Iq2d")
    return _struct_q2Iq2d
